# Generated by Django 4.1.7 on 2023-03-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user_message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.CharField(blank=True, max_length=150, null=True)),
                ("phone", models.CharField(max_length=120)),
                ("message", models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
